#!/usr/bin/env python3
"""Sole producer of the ForthOS GRUB-PXE grub.cfg.

Single source of truth: the FOS-UG* CONSTANT lines in
forth/dict/install.fth (the only GUID literals in the project).
The scan is FATAL on zero hits and on multiple hits per cell.

Mechanism: GRUB's search command has NO --part-uuid mode at all
(grub-pc 2.12 ships search_fs_file / search_fs_uuid /
search_label only).  probe.mod is GRUB's only GUID accessor, so
entry 1 loads biosdisk + part_gpt + probe + regexp + chain, then
walks every (hd*,gpt*) device with `probe --part-uuid` looking
for the canonical unique GUID.  probe returns LOWERCASE
(verified live 2026-08-09).

--override-guid exists solely for the harness's leg C (wrong-GUID
red leg) -- same generator, never a hand edit.

Entry order is FROZEN: 0 = memdisk (daily driver, timeout
fall-through), 1 = chainload. tests/test_grub_cfg.py pins it.
"""
import argparse
import re
import sys
import uuid

SCAN = re.compile(r'^([0-9A-F]{8}) CONSTANT FOS-UG([0-3])\s*$')


def scan_install_fth(path):
    """Return the four FOS-UG cells; fatal on 0 or >1 hits each."""
    hits = {}
    with open(path) as f:
        for n, line in enumerate(f, 1):
            m = SCAN.match(line.rstrip('\n'))
            if m:
                idx = int(m.group(2))
                hits.setdefault(idx, []).append(
                    (n, int(m.group(1), 16)))
    for idx in range(4):
        got = hits.get(idx, [])
        if len(got) != 1:
            sys.exit(f'FATAL: FOS-UG{idx}: {len(got)} hits in '
                     f'{path} (need exactly 1): {got}')
    return [hits[i][0][1] for i in range(4)]


def cells_to_uuid(cells):
    """Forth-!-order 32-bit LE cells -> lowercase RFC-4122 text.

    bytes_le is the GPT on-disk form; uuid.UUID(bytes_le=...) is
    the same independent authority used at mint time.
    """
    b = b''.join(c.to_bytes(4, 'little') for c in cells)
    return str(uuid.UUID(bytes_le=b)).lower()


TEMPLATE = """\
# Generated by tools/pxe/gen-grub-cfg.py -- DO NOT hand-edit.
# Drift gate: tests/test_grub_cfg.py (committed == generated).
# Entry order FROZEN: 0=memdisk (timeout fall-through), 1=chain.
set timeout=5
set default=0

menuentry "ForthOS - memdisk (dev)" {{
    linux16 /memdisk harddisk
    initrd16 /forth.img
}}

menuentry "ForthOS (installed to disk)" {{
    insmod biosdisk
    insmod part_gpt
    insmod probe
    insmod regexp
    insmod chain
    set found=
    for p in (hd*,gpt*); do
        probe --set puuid --part-uuid $p
        if [ "$puuid" = "{guid}" ]; then set root=$p; set found=1; fi
    done
    if [ "$found" = "1" ]; then chainloader +1; else echo "ForthOS: partition GUID not found"; sleep 5; fi
}}
"""


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--install-fth',
                    default='forth/dict/install.fth')
    ap.add_argument('--override-guid', default=None,
                    help='leg-C red cfg only; bypasses the scan')
    ap.add_argument('-o', '--output', default=None)
    args = ap.parse_args()
    if args.override_guid:
        guid = args.override_guid.lower()
    else:
        guid = cells_to_uuid(scan_install_fth(args.install_fth))
    cfg = TEMPLATE.format(guid=guid)
    if args.output:
        with open(args.output, 'w') as f:
            f.write(cfg)
    else:
        sys.stdout.write(cfg)


if __name__ == '__main__':
    main()
